name: Generate Resume

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq
          curl -L https://github.com/hairyhenderson/gomplate/releases/latest/download/gomplate_linux-amd64 -o /usr/local/bin/gomplate
          chmod +x /usr/local/bin/gomplate
          curl -L https://github.com/tectonic-typesetting/tectonic/releases/download/tectonic@0.15.0/tectonic-0.15.0-x86_64-unknown-linux-gnu.tar.gz | tar xz -C /usr/local/bin
          chmod +x /usr/local/bin/tectonic

      - name: Run generate script and commit changes
        run: |
          ./generate.sh -v
          # Skip if no changes
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "No changes to commit."
            exit 0
          fi
          # Commit and push changes
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add resume.pdf
          git commit -m "Re-generate resume"
          git push

      - name: Upload resume artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: resume.pdf