name: Generate Resume

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq
          curl -L https://github.com/hairyhenderson/gomplate/releases/latest/download/gomplate_linux-amd64 -o /usr/local/bin/gomplate
          chmod +x /usr/local/bin/gomplate
          curl -L https://github.com/tectonic-typesetting/tectonic/releases/download/tectonic@0.15.0/tectonic-0.15.0-x86_64-unknown-linux-gnu.tar.gz | tar xz -C /usr/local/bin
          chmod +x /usr/local/bin/tectonic

      - name: Run generate script
        run: 
          ./generate.sh
          # Skip if no changes.
          if [[ ! "$(git status --porcelain)" ]]; then
            echo "No changes."
            exit 0
          fi

          # Push code.
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Re-generate resume"
          git push